# Generated by Django 3.2.10 on 2022-02-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Описание услуги')),
                ('fixed_price', models.IntegerField(verbose_name='Фиксированная стоимость')),
                ('percent_price', models.IntegerField(help_text='Имеет приоритет', verbose_name='Процентная стоимость')),
                ('category', models.IntegerField(choices=[(1, 'Dota 2'), (2, 'CSGO')], verbose_name='Категория услуги')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='CSGOPriceBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование звания')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('order', models.IntegerField(verbose_name='Порядковый номер звания')),
            ],
            options={
                'verbose_name': 'СSGO Цена на буст',
                'verbose_name_plural': 'СSGO Цены на буст',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DOTAPriceBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmr', models.IntegerField(verbose_name='Число рейтинга')),
                ('price', models.IntegerField(verbose_name='Цена 50 MMR')),
            ],
            options={
                'verbose_name': 'Dota Цена на буст',
                'verbose_name_plural': 'Dota Цены на буст',
                'ordering': ['mmr'],
            },
        ),
    ]
