# Generated by Django 3.2.10 on 2022-02-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservice',
            name='fixed_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Фиксированная стоимость'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='percent_price',
            field=models.IntegerField(blank=True, help_text='Имеет приоритет', null=True, verbose_name='Процентная стоимость'),
        ),
        migrations.AlterField(
            model_name='dotapriceboost',
            name='price',
            field=models.IntegerField(verbose_name='Цена 100 MMR'),
        ),
    ]
