# Generated by Django 3.2.10 on 2022-02-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220207_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('category', models.IntegerField(choices=[('1', 'Dota Category'), ('2', 'Csgo Category'), ("[(1, 'Dota 2'), (2, 'CSGO')]", 'Category')], verbose_name='Игра')),
                ('is_published_landing', models.BooleanField(default=False, verbose_name='Отзыв опубликован')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'СSGO Цена на буст',
                'verbose_name_plural': 'СSGO Цены на буст',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='category',
            field=models.IntegerField(choices=[('1', 'Dota Category'), ('2', 'Csgo Category'), ("[(1, 'Dota 2'), (2, 'CSGO')]", 'Category')], verbose_name='Категория услуги'),
        ),
    ]
